import { PokemonNameType } from './db';

interface LevelEvolution {
    type: 'level';
    level: number;
}

interface RegionEvolution {
    type: 'region';
    region: string;
}

interface MegaEvolution {
    type: 'megaStone';
    megaStone: string;
}

interface StoneEvolution {
    type: 'stone';
    stone: string;
}

interface TimeEvolution {
    type: 'time';
    time: [number, number];
}

type BasicEvolutionType = LevelEvolution | MegaEvolution | StoneEvolution | TimeEvolution | RegionEvolution;

interface MultiEvolution {
    type: 'multi';
    requires: BasicEvolutionType[];
}

type AnyEvoType = BasicEvolutionType | MultiEvolution;

interface Evolution<EvoType> {
    to: PokemonNameType;
    requires: EvoType;
}

// Helper functions for evo requirements
const levelReq = (
    level: number,
): LevelEvolution => ({ type: 'level', level: level });

const stoneReq = (
    stone: string,
): StoneEvolution => ({ type: 'stone', stone: stone });

const megaReq = (
    megaStone: string,
): MegaEvolution => ({ type: 'megaStone', megaStone: megaStone });

const regionReq = (
    region: string,
): RegionEvolution => ({ type: 'region', region: region });

const timeReq = (
    startHour: number,
    endHour: number,
): TimeEvolution => ({ type: 'time', time: [startHour, endHour] });

const multiReq = (
    ...reqs: BasicEvolutionType[]
): MultiEvolution => ({ type: 'multi', requires: reqs });

// Helper functions for creating evolution definitions
const mkEvo = <T extends AnyEvoType>(
    toPoke: PokemonNameType,
    req: T,
): Evolution<T> => ({ to: toPoke, requires: req });

const levelEvo = (
    toPoke: PokemonNameType,
    atLevel: number,
) => mkEvo(toPoke, levelReq(atLevel));

const stoneEvo = (
    toPoke: PokemonNameType,
    stone: string,
) => mkEvo(toPoke, stoneReq(stone));

const megaEvo = (
    toPoke: PokemonNameType,
    megastone: string,
) => mkEvo(toPoke, megaReq(megastone));

// All evolution data
const EVOLUTIONS: Partial<Record<PokemonNameType, Evolution<AnyEvoType>[]>> = {
    'Bulbasaur': [levelEvo('Ivysaur', 16)],
    'Ivysaur': [levelEvo('Venusaur', 32)],
    'Venusaur': [megaEvo('M-Venusaur', 'venusaurite')],
    'Charmander': [levelEvo('Charmeleon', 16)],
    'Charmeleon': [levelEvo('Charizard', 36)],
    'Charizard': [
        megaEvo('M-Charizard X', 'charizarditeX'),
        megaEvo('M-Charizard Y', 'charizarditeY'),
    ],
    'Squirtle': [levelEvo('Wartortle', 16)],
    'Wartortle': [levelEvo('Blastoise', 36)],
    'Blastoise': [megaEvo('M-Blastoise', 'blastoisinite')],
    'Caterpie': [levelEvo('Metapod', 7)],
    'Metapod': [levelEvo('Butterfree', 10)],
    'Weedle': [levelEvo('Kakuna', 7)],
    'Kakuna': [levelEvo('Beedrill', 10)],
    'Pidgey': [levelEvo('Pidgeotto', 18)],
    'Pidgeotto': [levelEvo('Pidgeot', 36)],
    'Pidgeot': [megaEvo('M-Pidgeot', 'pidgeotite')],
    'Rattata': [levelEvo('Raticate', 20)],
    'Alolan Rattata': [levelEvo('Alolan Raticate', 20)],
    'Spearow': [levelEvo('Fearow', 20)],
    'Ekans': [levelEvo('Arbok', 22)],
    'Pichu': [stoneEvo('Pikachu', 'sootheBell')],
    'Pikachu': [
        stoneEvo('Raichu', 'thunderStone'),
        mkEvo('Alolan Raichu', multiReq(stoneReq('thunderStone'), regionReq('Alola'))),
    ],
    'Sandshrew': [levelEvo('Sandslash', 22)],
    'Alolan Sandshrew': [stoneEvo('Alolan Sandslash', 'iceStone')],
    'Nidoran F': [levelEvo('Nidorina', 16)],
    'Nidorina': [stoneEvo('Nidoqueen', 'moonStone')],
    'Nidoran M': [levelEvo('Nidorino', 16)],
    'Nidorino': [stoneEvo('Nidoking', 'moonStone')],
    'Cleffa': [stoneEvo('Clefairy', 'sootheBell')],
    'Clefairy': [stoneEvo('Clefable', 'moonStone')],
    'Vulpix': [stoneEvo('Ninetales', 'fireStone')],
    'Alolan Vulpix': [stoneEvo('Alolan Ninetales', 'iceStone')],
    'Igglybuff': [stoneEvo('Jigglypuff', 'sootheBell')],
    'Jigglypuff': [stoneEvo('Wigglytuff', 'moonStone')],
    'Zubat': [levelEvo('Golbat', 22)],
    'Golbat': [stoneEvo('Crobat', 'sootheBell')],
    'Oddish': [levelEvo('Gloom', 21)],
    'Gloom': [
        stoneEvo('Vileplume', 'leafStone'),
        stoneEvo('Bellossom', 'sunStone'),
    ],
    'Paras': [levelEvo('Parasect', 24)],
    'Venonat': [levelEvo('Venomoth', 31)],
    'Diglett': [levelEvo('Dugtrio', 26)],
    'Alolan Diglett': [levelEvo('Alolan Dugtrio', 26)],
    'Meowth': [levelEvo('Persian', 28)],
    'Alolan Meowth': [levelEvo('Alolan Persian', 28)],
    'Psyduck': [levelEvo('Golduck', 33)],
    'Mankey': [levelEvo('Primeape', 28)],
    'Growlithe': [stoneEvo('Arcanine', 'fireStone')],
    'Poliwag': [levelEvo('Poliwhirl', 25)],
    'Poliwhirl': [
        stoneEvo('Poliwrath', 'waterStone'),
        stoneEvo('Politoed', 'sunStone'),
    ],
    'Abra': [levelEvo('Kadabra', 16)],
    'Alakazam': [megaEvo('M-Alakazam', 'alakazite')],
    'Kangaskhan': [megaEvo('M-Kangaskhan', 'kangaskhanite')],
    'Pinsir': [megaEvo('M-Pinsir', 'pinsirite')],
    'Machop': [levelEvo('Machoke', 28)],
    'Bellsprout': [levelEvo('Weepinbell', 21)],
    'Weepinbell': [stoneEvo('Victreebel', 'leafStone')],
    'Tentacool': [levelEvo('Tentacruel', 30)],
    'Geodude': [levelEvo('Graveler', 25)],
    'Alolan Geodude': [levelEvo('Alolan Graveler', 25)],
    'Alolan Graveler': [levelEvo('Alolan Golem', 40)],
    'Ponyta': [levelEvo('Rapidash', 40)],
    'Slowpoke': [levelEvo('Slowbro', 37)],
    'Slowbro': [
        megaEvo('M-Slowbro', 'slowbronite'),
        stoneEvo('Slowking', 'kingsRock'),
    ],
    'Magnemite': [levelEvo('Magneton', 30)],
    'Doduo': [levelEvo('Dodrio', 31)],
    'Seel': [levelEvo('Dewgong', 34)],
    'Grimer': [levelEvo('Muk', 38)],
    'Alolan Grimer': [levelEvo('Alolan Muk', 38)],
    'Shellder': [stoneEvo('Cloyster', 'waterStone')],
    'Gastly': [levelEvo('Haunter', 25)],
    'Haunter': [levelEvo('Gengar', 40)],
    'Gengar': [megaEvo('M-Gengar', 'gengarite')],
    'Drowzee': [levelEvo('Hypno', 26)],
    'Krabby': [levelEvo('Kingler', 28)],
    'Voltorb': [levelEvo('Electrode', 30)],
    'Exeggcute': [
        stoneEvo('Exeggutor', 'leafStone'),
        mkEvo('Alolan Exeggutor', multiReq(stoneReq('leafStone'), regionReq('Alola'))),
    ],
    'Cubone': [
        levelEvo('Marowak', 28),
        mkEvo('Alolan Marowak', multiReq(levelReq(28), regionReq('Alola'))),
    ],
    'Koffing': [levelEvo('Weezing', 35)],
    'Rhyhorn': [levelEvo('Rhydon', 42)],
    'Horsea': [levelEvo('Seadra', 32)],
    'Seadra': [stoneEvo('Kingdra', 'dragonScale')],
    'Goldeen': [levelEvo('Seaking', 32)],
    'Staryu': [stoneEvo('Starmie', 'waterStone')],
    'Magikarp': [levelEvo('Gyarados', 20)],
    'Gyarados': [megaEvo('M-Gyarados', 'gyaradosite')],
    'Aerodactyl': [megaEvo('M-Aerodactyl', 'aerodactylite')],
    'Eevee': [
        stoneEvo('Flareon', 'fireStone'),
        mkEvo('Espeon', multiReq(levelReq(30), timeReq(6, 18))),
        mkEvo('Umbreon', multiReq(levelReq(30), timeReq(18, 6))),
        stoneEvo('Jolteon', 'thunderStone'),
        stoneEvo('Vaporeon', 'waterStone'),
        stoneEvo('Leafeon', 'leafStone'),
        stoneEvo('Glaceon', 'iceStone'),
    ],
    'Omanyte': [levelEvo('Omastar', 40)],
    'Kabuto': [levelEvo('Kabutops', 40)],
    'Dratini': [levelEvo('Dragonair', 30)],
    'Dragonair': [levelEvo('Dragonite', 55)],
    'Mewtwo': [
        megaEvo('M-Mewtwo X', 'mewtwoniteX'),
        megaEvo('M-Mewtwo Y', 'mewtwoniteY'),
    ],
    'Chikorita': [levelEvo('Bayleef', 16)],
    'Bayleef': [levelEvo('Meganium', 32)],
    'Cyndaquil': [levelEvo('Quilava', 14)],
    'Quilava': [levelEvo('Typhlosion', 36)],
    'Totodile': [levelEvo('Croconaw', 18)],
    'Croconaw': [levelEvo('Feraligatr', 30)],
    'Sentret': [levelEvo('Furret', 15)],
    'Hoothoot': [levelEvo('Noctowl', 20)],
    'Ledyba': [levelEvo('Ledian', 18)],
    'Spinarak': [levelEvo('Ariados', 22)],
    'Chinchou': [levelEvo('Lanturn', 27)],
    'Togepi': [stoneEvo('Togetic', 'sootheBell')],
    'Togetic': [stoneEvo('Togekiss', 'shinyStone')],
    'Natu': [levelEvo('Xatu', 25)],
    'Mareep': [levelEvo('Flaaffy', 15)],
    'Flaaffy': [levelEvo('Ampharos', 30)],
    'Ampharos': [megaEvo('M-Ampharos', 'ampharosite')],
    'Azurill': [stoneEvo('Marill', 'sootheBell')],
    'Marill': [levelEvo('Azumarill', 18)],
    'Hoppip': [levelEvo('Skiploom', 18)],
    'Skiploom': [levelEvo('Jumpluff', 27)],
    'Bonsly': [stoneEvo('Sudowoodo', 'sootheBell')],
    'Porygon': [stoneEvo('Porygon2', 'upGrade')],
    'Scyther': [stoneEvo('Scizor', 'metalCoat')],
    'Heracross': [megaEvo('M-Heracross', 'heracronite')],
    'Scizor': [megaEvo('M-Scizor', 'scizorite')],
    'Sunkern': [stoneEvo('Sunflora', 'sunStone')],
    'Wooper': [levelEvo('Quagsire', 20)],
    'Pineco': [levelEvo('Forretress', 31)],
    'Onix': [stoneEvo('Steelix', 'metalCoat')],
    'Steelix': [megaEvo('M-Steelix', 'steelixite')],
    'Snubbull': [levelEvo('Granbull', 23)],
    'Teddiursa': [levelEvo('Ursaring', 30)],
    'Slugma': [levelEvo('Magcargo', 38)],
    'Swinub': [levelEvo('Piloswine', 33)],
    'Remoraid': [levelEvo('Octillery', 25)],
    'Houndour': [levelEvo('Houndoom', 24)],
    'Houndoom': [megaEvo('M-Houndoom', 'houndoominite')],
    'Phanpy': [levelEvo('Donphan', 25)],
    'Tyrogue': [levelEvo('Hitmontop', 20)],
    'Larvitar': [levelEvo('Pupitar', 30)],
    'Pupitar': [levelEvo('Tyranitar', 55)],
    'Tyranitar': [megaEvo('M-Tyranitar', 'tyranitarite')],
    'Landorus': [stoneEvo('Landorus-T', 'revealGlass')],
    'Tornadus': [stoneEvo('Tornadus-T', 'revealGlass')],
    'Thundurus': [stoneEvo('Thundurus-T', 'revealGlass')],
    'Treecko': [levelEvo('Grovyle', 16)],
    'Grovyle': [levelEvo('Sceptile', 36)],
    'Sceptile': [megaEvo('M-Sceptile', 'sceptilite')],
    'Torchic': [levelEvo('Combusken', 16)],
    'Combusken': [levelEvo('Blaziken', 36)],
    'Blaziken': [megaEvo('M-Blaziken', 'blazikenite')],
    'Mudkip': [levelEvo('Marshtomp', 16)],
    'Marshtomp': [levelEvo('Swampert', 36)],
    'Swampert': [megaEvo('M-Swampert', 'swampertite')],
    'Poochyena': [levelEvo('Mightyena', 18)],
    'Zigzagoon': [levelEvo('Linoone', 20)],
    'Wurmple': [levelEvo('Silcoon', 7)],
    'Silcoon': [levelEvo('Beautifly', 10)],
    'Lotad': [levelEvo('Lombre', 14)],
    'Lombre': [stoneEvo('Ludicolo', 'waterStone')],
    'Seedot': [levelEvo('Nuzleaf', 14)],
    'Nuzleaf': [stoneEvo('Shiftry', 'leafStone')],
    'Taillow': [levelEvo('Swellow', 22)],
    'Wingull': [levelEvo('Pelipper', 25)],
    'Ralts': [levelEvo('Kirlia', 20)],
    'Kirlia': [
        levelEvo('Gardevoir', 30),
        levelEvo('Gallade', 30),
    ],
    'Gardevoir': [megaEvo('M-Gardevoir', 'gardevoirite')],
    'Gallade': [megaEvo('M-Gallade', 'galladite')],
    'Sableye': [megaEvo('M-Sableye', 'sablenite')],
    'Mawile': [megaEvo('M-Mawile', 'mawilite')],
    'Surskit': [levelEvo('Masquerain', 22)],
    'Shroomish': [levelEvo('Breloom', 23)],
    'Slakoth': [levelEvo('Vigoroth', 18)],
    'Vigoroth': [levelEvo('Slaking', 36)],
    'Nincada': [levelEvo('Ninjask', 20)],
    'Whismur': [levelEvo('Loudred', 20)],
    'Loudred': [levelEvo('Exploud', 40)],
    'Makuhita': [levelEvo('Hariyama', 24)],
    'Nosepass': [levelEvo('Probopass', 35)],
    'Skitty': [stoneEvo('Delcatty', 'moonStone')],
    'Aron': [levelEvo('Lairon', 32)],
    'Lairon': [levelEvo('Aggron', 42)],
    'Aggron': [megaEvo('M-Aggron', 'aggronite')],
    'Meditite': [levelEvo('Medicham', 37)],
    'Medicham': [megaEvo('M-Medicham', 'medichamite')],
    'Electrike': [levelEvo('Manectric', 37)],
    'Manectric': [megaEvo('M-Manectric', 'manectite')],
    'Budew': [levelEvo('Roselia', 12)],
    'Roselia': [levelEvo('Roserade', 27)],
    'Gulpin': [levelEvo('Swalot', 26)],
    'Carvanha': [levelEvo('Sharpedo', 30)],
    'Sharpedo': [megaEvo('M-Sharpedo', 'sharpedonite')],
    'Wailmer': [levelEvo('Wailord', 40)],
    'Numel': [levelEvo('Camerupt', 33)],
    'Camerupt': [megaEvo('M-Camerupt', 'cameruptite')],
    'Spoink': [levelEvo('Grumpig', 32)],
    'Trapinch': [levelEvo('Vibrava', 35)],
    'Vibrava': [levelEvo('Flygon', 45)],
    'Cacnea': [levelEvo('Cacturne', 32)],
    'Swablu': [levelEvo('Altaria', 35)],
    'Altaria': [megaEvo('M-Altaria', 'altarianite')],
    'Barboach': [levelEvo('Whiscash', 30)],
    'Corphish': [levelEvo('Crawdaunt', 30)],
    'Baltoy': [levelEvo('Claydol', 36)],
    'Lileep': [levelEvo('Cradily', 40)],
    'Anorith': [levelEvo('Armaldo', 40)],
    'Feebas': [levelEvo('Milotic', 40)],
    'Shuppet': [levelEvo('Banette', 37)],
    'Banette': [megaEvo('M-Banette', 'banettite')],
    'Absol': [megaEvo('M-Absol', 'absolite')],
    'Duskull': [levelEvo('Dusclops', 37)],
    'Dusclops': [levelEvo('Dusknoir', 50)],
    'Chingling': [levelEvo('Chimecho', 20)],
    'Snorunt': [levelEvo('Glalie', 42)],
    'Glalie': [megaEvo('M-Glalie', 'glalitite')],
    'Spheal': [levelEvo('Sealeo', 32)],
    'Sealeo': [levelEvo('Walrein', 44)],
    'Clamperl': [levelEvo('Gorebyss', 30)],
    'Bagon': [levelEvo('Shelgon', 30)],
    'Shelgon': [levelEvo('Salamence', 50)],
    'Salamence': [megaEvo('M-Salamence', 'salamencite')],
    'Beldum': [levelEvo('Metang', 20)],
    'Metang': [levelEvo('Metagross', 45)],
    'Metagross': [megaEvo('M-Metagross', 'metagrossite')],
    'Latias': [megaEvo('M-Latias', 'latiasite')],
    'Latios': [megaEvo('M-Latios', 'latiosite')],
    'Rayquaza': [megaEvo('M-Rayquaza', 'rayquazite')],
    'Lopunny': [megaEvo('M-Lopunny', 'lopunnite')],
    'Gible': [levelEvo('Gabite', 24)],
    'Gabite': [levelEvo('Garchomp', 48)],
    'Garchomp': [megaEvo('M-Garchomp', 'garchompite')],
    'Lucario': [megaEvo('M-Lucario', 'lucarionite')],
    'Abomasnow': [megaEvo('M-Abomasnow', 'abomasite')],
    'Snivy': [levelEvo('Servine', 17)],
    'Servine': [levelEvo('Serperior', 36)],
    'Tepig': [levelEvo('Pignite', 17)],
    'Pignite': [levelEvo('Emboar', 36)],
    'Oshawott': [levelEvo('Dewott', 17)],
    'Dewott': [levelEvo('Samurott', 36)],
    'Patrat': [levelEvo('Watchog', 20)],
    'Purrloin': [levelEvo('Liepard', 20)],
    'Pidove': [levelEvo('Tranquill', 21)],
    'Tranquill': [levelEvo('Unfezant', 32)],
    'Sewaddle': [levelEvo('Swadloon', 20)],
    'Swadloon': [stoneEvo('Leavanny', 'sootheBell')],
    'Lillipup': [levelEvo('Herdier', 16)],
    'Herdier': [levelEvo('Stoutland', 32)],
    'Pansage': [stoneEvo('Simisage', 'leafStone')],
    'Pansear': [stoneEvo('Simisear', 'fireStone')],
    'Panpour': [stoneEvo('Simipour', 'waterStone')],
    'Woobat': [stoneEvo('Swoobat', 'sootheBell')],
    'Venipede': [levelEvo('Whirlipede', 22)],
    'Whirlipede': [levelEvo('Scolipede', 30)],
    'Roggenrola': [levelEvo('Boldore', 25)],
    'Boldore': [levelEvo('Gigalith', 40)],
    'Timburr': [levelEvo('Gurdurr', 25)],
    'Gurdurr': [levelEvo('Conkeldurr', 40)],
    'Drilbur': [levelEvo('Excadrill', 31)],
    'Cottonee': [stoneEvo('Whimsicott', 'sunStone')],
    'Petilil': [stoneEvo('Lilligant', 'sunStone')],
    'Munna': [stoneEvo('Musharna', 'moonStone')],
    'Sandile': [levelEvo('Krokorok', 29)],
    'Krokorok': [levelEvo('Krookodile', 40)],
    'Darumaka': [levelEvo('Darmanitan', 35)],
    'Trubbish': [levelEvo('Garbodor', 36)],
    'Minccino': [stoneEvo('Cinccino', 'shinyStone')],
    'Rufflet': [levelEvo('Braviary', 54)],
    'Vullaby': [levelEvo('Mandibuzz', 54)],
    'Dwebble': [levelEvo('Crustle', 34)],
    'Scraggy': [levelEvo('Scrafty', 39)],
    'Yamask': [levelEvo('Cofagrigus', 34)],
    'Tirtouga': [levelEvo('Carracosta', 37)],
    'Archen': [levelEvo('Archeops', 37)],
    'Klink': [levelEvo('Klang', 38)],
    'Klang': [levelEvo('Klinklang', 49)],
    'Gothita': [levelEvo('Gothorita', 32)],
    'Gothorita': [levelEvo('Gothitelle', 41)],
    'Solosis': [levelEvo('Duosion', 32)],
    'Duosion': [levelEvo('Reuniclus', 41)],
    'Blitzle': [levelEvo('Zebstrika', 27)],
    'Zorua': [levelEvo('Zoroark', 30)],
    'Ducklett': [levelEvo('Swanna', 35)],
    'Karrablast': [levelEvo('Escavalier', 40)],
    'Shelmet': [levelEvo('Accelgor', 40)],
    'Deerling': [levelEvo('Sawsbuck', 34)],
    'Foongus': [levelEvo('Amoonguss', 39)],
    'Larvesta': [levelEvo('Volcarona', 59)],
    'Joltik': [levelEvo('Galvantula', 36)],
    'Ferroseed': [levelEvo('Ferrothorn', 40)],
    'Tynamo': [levelEvo('Eelektrik', 39)],
    'Axew': [levelEvo('Fraxure', 38)],
    'Fraxure': [levelEvo('Haxorus', 48)],
    'Eelektrik': [stoneEvo('Eelektross', 'thunderStone')],
    'Frillish': [levelEvo('Jellicent', 40)],
    'Elgyem': [levelEvo('Beheeyem', 42)],
    'Litwick': [levelEvo('Lampent', 41)],
    'Lampent': [stoneEvo('Chandelure', 'duskStone')],
    'Cubchoo': [levelEvo('Beartic', 37)],
    'Mienfoo': [levelEvo('Mienshao', 50)],
    'Pawniard': [levelEvo('Bisharp', 52)],
    'Tympole': [levelEvo('Palpitoad', 25)],
    'Palpitoad': [levelEvo('Seismitoad', 36)],
    'Vanillite': [levelEvo('Vanillish', 35)],
    'Vanillish': [levelEvo('Vanilluxe', 47)],
    'Golett': [levelEvo('Golurk', 43)],
    'Deino': [levelEvo('Zweilous', 50)],
    'Zweilous': [levelEvo('Hydreigon', 64)],
    'Audino': [megaEvo('M-Audino', 'audinite')],
    'Diancie': [megaEvo('M-Diancie', 'diancite')],
    'Froakie': [levelEvo('Frogadier', 16)],
    'Frogadier': [levelEvo('Greninja', 36)],
    'Fennekin': [levelEvo('Braixen', 16)],
    'Braixen': [levelEvo('Delphox', 36)],
    'Chespin': [levelEvo('Quilladin', 16)],
    'Quilladin': [levelEvo('Chesnaught', 36)],
    'Fletchling': [levelEvo('Fletchinder', 17)],
    'Fletchinder': [levelEvo('Talonflame', 35)],
    'Scatterbug': [levelEvo('Spewpa', 9)],
    'Spewpa': [levelEvo('Vivillon', 12)],
    'Bunnelby': [levelEvo('Diggersby', 20)],
    'Litleo': [levelEvo('Pyroar', 35)],
    'Skiddo': [levelEvo('Gogoat', 32)],
    'Flabebe': [levelEvo('Floette', 19)],
    'Floette': [stoneEvo('Florges', 'shinyStone')],
    'Pancham': [levelEvo('Pangoro', 32)],
    'Espurr': [levelEvo('Meowstic', 25)],
    'Honedge': [levelEvo('Doublade', 35)],
    'Doublade': [stoneEvo('Aegislash', 'duskStone')],
    'Spritzee': [stoneEvo('Aromatisse', 'sachet')],
    'Swirlix': [stoneEvo('Slurpuff', 'whippedDream')],
    'Inkay': [levelEvo('Malamar', 30)],
    'Binacle': [levelEvo('Barbaracle', 39)],
    'Skrelp': [levelEvo('Dragalge', 48)],
    'Clauncher': [levelEvo('Clawitzer', 37)],
    'Tyrunt': [levelEvo('Tyrantrum', 39)],
    'Amaura': [levelEvo('Aurorus', 39)],
    'Helioptile': [stoneEvo('Heliolisk', 'sunStone')],
    'Goomy': [levelEvo('Sliggoo', 40)],
    'Sliggoo': [levelEvo('Goodra', 50)],
    'Phantump': [levelEvo('Trevenant', 40)],
    'Pumpkaboo': [levelEvo('Gourgeist', 40)],
    'Bergmite': [levelEvo('Avalugg', 37)],
    'Noibat': [levelEvo('Noivern', 48)],
    'Popplio': [levelEvo('Brionne', 17)],
    'Brionne': [levelEvo('Primarina', 34)],
    'Litten': [levelEvo('Torracat', 17)],
    'Torracat': [levelEvo('Incineroar', 34)],
    'Rowlet': [levelEvo('Dartrix', 17)],
    'Dartrix': [levelEvo('Decidueye', 34)],
    'Turtwig': [levelEvo('Grotle', 18)],
    'Grotle': [levelEvo('Torterra', 32)],
    'Chimchar': [levelEvo('Monferno', 14)],
    'Monferno': [levelEvo('Infernape', 36)],
    'Piplup': [levelEvo('Prinplup', 16)],
    'Prinplup': [levelEvo('Empoleon', 36)],
    'Starly': [levelEvo('Staravia', 14)],
    'Staravia': [levelEvo('Staraptor', 34)],
    'Bidoof': [levelEvo('Bibarel', 15)],
    'Kricketot': [levelEvo('Kricketune', 10)],
    'Shinx': [levelEvo('Luxio', 15)],
    'Luxio': [levelEvo('Luxray', 30)],
    'Cranidos': [levelEvo('Rampardos', 30)],
    'Shieldon': [levelEvo('Bastiodon', 30)],
    'Burmy': [levelEvo('Wormadam', 20)],
    'Wormadam': [levelEvo('Mothim', 20)],
    'Combee': [levelEvo('Vespiquen', 21)],
    'Cherubi': [levelEvo('Cherrim', 21)],
    'Buizel': [levelEvo('Floatzel', 26)],
    'Aipom': [levelEvo('Ambipom', 30)],
    'Drifloon': [levelEvo('Drifblim', 28)],
    'Buneary': [stoneEvo('Lopunny', 'sootheBell')],
    'Misdreavus': [stoneEvo('Mismagius', 'duskStone')],
    'Murkrow': [stoneEvo('Honchkrow', 'duskStone')],
    'Glameow': [levelEvo('Purugly', 38)],
    'Stunky': [levelEvo('Skuntank', 34)],
    'Bronzor': [levelEvo('Bronzong', 33)],
    'Mime Jr.': [stoneEvo('Mr. Mime', 'sootheBell')],
    'Happiny': [stoneEvo('Chansey', 'sootheBell')],
    'Chansey': [stoneEvo('Blissey', 'sootheBell')],
    'Munchlax': [stoneEvo('Snorlax', 'sootheBell')],
    'Riolu': [mkEvo('Lucario', multiReq(stoneReq('sootheBell'), timeReq(6, 18)))],
    'Hippopotas': [levelEvo('Hippowdon', 34)],
    'Skorupi': [levelEvo('Drapion', 40)],
    'Croagunk': [levelEvo('Toxicroak', 37)],
    'Finneon': [levelEvo('Lumineon', 31)],
    'Mantyke': [stoneEvo('Mantine', 'sootheBell')],
    'Snover': [levelEvo('Abomasnow', 40)],
    'Sneasel': [stoneEvo('Weavile', 'duskStone')],
    'Magneton': [stoneEvo('Magnezone', 'thunderStone')],
    'Lickitung': [stoneEvo('Lickilicky', 'moonStone')],
    'Rhydon': [stoneEvo('Rhyperior', 'Protector')],
    'Tangela': [levelEvo('Tangrowth', 90)],
    'Electabuzz': [stoneEvo('Electivire', 'thunderStone')],
    'Magmar': [stoneEvo('Magmortar', 'fireStone')],
    'Yanma': [levelEvo('Yanmega', 50)],
    'Gligar': [stoneEvo('Gliscor', 'duskStone')],
    'Piloswine': [stoneEvo('Mamoswine', 'iceStone')],
    'Porygon2': [levelEvo('Porygon-Z', 90)],
    'Pikipek': [levelEvo('Trumbeak', 14)],
    'Trumbeak': [levelEvo('Toucannon', 28)],
    'Yungoos': [levelEvo('Gumshoos', 20)],
    'Grubbin': [levelEvo('Charjabug', 20)],
    'Charjabug': [levelEvo('Vikavolt', 40)],
    'Crabrawler': [
        { 'to': 'Crabominable', 'requires': { 'type': 'region', 'region': 'Alola' } },
    ],
    'Cutiefly': [levelEvo('Ribombee', 25)],
    'Rockruff': [
        mkEvo('Lycanroc', multiReq(levelReq(25), timeReq(6, 18))),
        mkEvo('Lycanroc-M', multiReq(levelReq(25), timeReq(18, 6))),
        mkEvo('Lycanroc-D', multiReq(levelReq(25), regionReq('Alola'))),
    ],
    'Mareanie': [levelEvo('Toxapex', 38)],
    'Mudbray': [levelEvo('Mudsdale', 30)],
    'Dewpider': [levelEvo('Araquanid', 22)],
    'Fomantis': [levelEvo('Lurantis', 34)],
    'Morelull': [levelEvo('Shiinotic', 24)],
    'Salandit': [levelEvo('Salazzle', 33)],
    'Stufful': [levelEvo('Bewear', 27)],
    'Bounsweet': [levelEvo('Steenee', 18)],
    'Steenee': [levelEvo('Tsareena', 40)],
    'Wimpod': [levelEvo('Golisopod', 30)],
    'Sandygast': [levelEvo('Palossand', 42)],
    'Jangmo-o': [levelEvo('Hakamo-o', 35)],
    'Hakamo-o': [levelEvo('Kommo-o', 45)],
    'Type: Null': [stoneEvo('Silvally', 'sootheBell')],
    'Cosmog': [levelEvo('Cosmoem', 43)],
    'Cosmoem': [
        mkEvo('Solgaleo', multiReq(levelReq(53), timeReq(6, 18))),
        mkEvo('Lunala', multiReq(levelReq(53), timeReq(18, 6))),
    ],
};

export default EVOLUTIONS;
