<template>
  <div id="regionBox">
    <div id="regionSelect">
      <span>REGION SELECT</span><br>
      <button
        id="kantoButton"
        onclick="userInteractions.goToKanto()"
        class="button"
        value="Kanto"
      >
        KANTO
      </button>
      <button
        id="johtoButton"
        onclick="userInteractions.goToJohto()"
        class="button"
        value="Johto"
      >
        JOHTO
      </button>
      <button
        id="hoennButton"
        onclick="userInteractions.goToHoenn()"
        class="button"
        value="Hoenn"
      >
        HOENN
      </button><br>
      <button
        id="sinnohButton"
        onclick="userInteractions.goToSinnoh()"
        class="button"
        value="Sinnoh"
      >
        SINNOH
      </button>
      <button
        id="unovaButton"
        onclick="userInteractions.goToUnova()"
        class="button"
        value="Unova"
      >
        UNOVA
      </button>
      <button
        id="kalosButton"
        onclick="userInteractions.goToKalos()"
        class="button"
        value="Kalos"
      >
        KALOS
      </button><br>
      <button
        id="alolaButton"
        onclick="userInteractions.goToAlola()"
        class="button"
        value="Alola"
      >
        ALOLA
      </button>
      <button
        id="galarButton"
        onclick="userInteractions.goToNone()"
        class="button"
        value="Galar"
      >
        GALAR
      </button><br>
    </div>
  </div>
</template>
