<template>
  <div id="regionSelect">
    <span>Region Select</span>
    <div id="regionButtons">
      <button
        id="kantoButton"
        class="button"
        value="Kanto"
        onclick="userInteractions.goToDifferentRegion('Kanto')"
      >
        KANTO
      </button>
      <button
        id="johtoButton"
        class="button"
        onclick="userInteractions.goToDifferentRegion('Johto')"
      >
        JOHTO
      </button>
      <button
        id="hoennButton"
        class="button"
        onclick="userInteractions.goToDifferentRegion('Hoenn')"
      >
        HOENN
      </button>
      <button
        id="sinnohButton"
        class="button"
        value="Sinnoh"
        onclick="userInteractions.goToDifferentRegion('Sinnoh')"
      >
        SINNOH
      </button>
      <button
        id="unovaButton"
        class="button"
        value="Unova"
        onclick="userInteractions.goToDifferentRegion('Unova')"
      >
        UNOVA
      </button>
      <button
        id="kalosButton"
        class="button"
        value="Kalos"
        onclick="userInteractions.goToNone()"
      >
        KALOS
      </button>
      <button
        id="alolaButton"
        class="button"
        value="Alola"
        onclick="userInteractions.goToNone()"
      >
        ALOLA
      </button>
      <button
        id="galarButton"
        class="button"
        value="Galar"
        onclick="userInteractions.goToNone()"
      >
        GALAR
      </button>
      <button
        id="fandomButton"
        class="button"
        value="Fandom"
        onclick="userInteractions.goToDifferentRegion('Fandom')"
      >
        FANDOM
      </button><br>
    </div>
  </div>
</template>
