<template>
  <div id="viewSelectBox">
    <p>
      <button
        id="heal"
        class="button-old"
      >
        Heal
      </button>
    </p>
    <p>
      <button
        id="viewRoster"
        class="button-old"
      >
        Pokemon
      </button>
    </p>
    <p>
      <button
        id="viewStorage"
        class="button-old"
      >
        Storage
      </button>
    </p>
    <p>
      <button
        id="viewPokeDex"
        class="button-old"
      >
        PokeDex
      </button>
    </p>
  </div>
</template>
